//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newco7
{
    using System;
    
    public enum DaysOfTheWeek : int
    {
        Monday = 1,
        Tuesday = 2,
        Wednesday = 3,
        Thrusday = 4,
        Friday = 5,
        Saturaday = 6,
        Sunday = 7
    }
}
