//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newco7
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTasks : Tasks
    {
        public int ProjectTaskId { get; set; }
        public Nullable<int> ProjectsProjectId { get; set; }
    
        public virtual Projects Project { get; set; }
    }
}
