//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newco7
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesUsers : User
    {
        public int UserUserId { get; set; }
    
        public virtual User User1 { get; set; }
    }
}
