//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newco7
{
    using System;
    
    public enum SecurityModels : int
    {
        Projects = 0,
        Email_Designer = 1,
        Scheduler = 2,
        Segmentation = 3,
        Campaigns = 4,
        Subscribers = 5,
        Administration = 6,
        Reports = 7,
        Opportunities = 8
    }
}
