//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newco7
{
    using System;
    
    public enum SecurityLevels : int
    {
        Default = 0,
        Administrator = 1,
        Executive = 2
    }
}
