//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newco7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int ServiceId { get; set; }
        public int AssociationsAssociationId { get; set; }
    
        public virtual Associations Association { get; set; }
    }
}
