//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newco7.Tests
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NEWCO7COREContainer : DbContext
    {
        public NEWCO7COREContainer()
            : base("name=NEWCO7COREContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Passwords> Passwords { get; set; }
        public virtual DbSet<SecurityAccessByModules> SecurityAccessByModules { get; set; }
        public virtual DbSet<SecurityLevels> SecurityLevels { get; set; }
    }
}
